name: Docker CI Pipeline

on:
  pull_request:
    branches:
      - feature-branch  

env:
  IMAGE_NAME: express-app
  CONTAINER_NAME: assignment1
  PORT: 8080

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Build Docker Image
      run: docker build -t $IMAGE_NAME .

    - name: Save Docker Image as Tar
      run: docker save $IMAGE_NAME > express-app.tar

    - name: Upload Docker Image as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: docker-image
        path: express-app.tar

  run:
    name: Run Docker Container
    runs-on: ubuntu-latest
    needs: build  # Depends on 'build' job to complete successfully

    steps:
    - name: Download Docker Image Artifact
      uses: actions/download-artifact@v3
      with:
        name: docker-image

    - name: Load Docker Image
      run: docker load < express-app.tar

    - name: Run the Docker Container
      run: |
        docker run -d --name $CONTAINER_NAME -p $PORT:$PORT express-app

    - name: Verify Container is Running
      run: docker ps -a

  stop:
    name: Stop Docker Container
    runs-on: ubuntu-latest
    needs: run  # Depends on the 'run' job to ensure the container is active

    steps:
    - name: Stop and Remove Container
      run: |
        docker stop $CONTAINER_NAME || true
        docker rm $CONTAINER_NAME || true
