name: Docker CI Pipeline

on:
  push:
    branches:
      - feature 

env:
  IMAGE_NAME: express-app
  CONTAINER_NAME: assignment1
  PORT: 8080  # Port configuration

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build Docker Image
      run: |
        docker build -t $IMAGE_NAME:${{ github.sha }} .
        echo $IMAGE_NAME:${{ github.sha }} > image.txt  # Store image name with tag

    - name: Upload Image Tag Artifact
      uses: actions/upload-artifact@v3
      with:
        name: docker-image-tag
        path: image.txt

  run:
    name: Run Docker Container
    runs-on: ubuntu-latest
    needs: build  # Ensure this job runs after 'build'

    steps:
    - name: Download Image Tag Artifact
      uses: actions/download-artifact@v3
      with:
        name: docker-image-tag

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Run the Docker Container
      run: |
        IMAGE_TAG=$(cat image.txt)
        docker run -d --name $CONTAINER_NAME -p $PORT:$PORT $IMAGE_TAG

    - name: Verify Container is Running
      run: docker ps -a

  stop:
    name: Stop Docker Container
    runs-on: ubuntu-latest
    needs: run  # Ensure this job runs after 'run'

    steps:
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Stop and Remove Container
      run: |
        docker stop $CONTAINER_NAME || true
        docker rm $CONTAINER_NAME || true
